<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGHxl3m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGHxl3m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZGHxl3m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZGHxl3m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZGHxl3m\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZGHxl3m',
    'container.build_id' => '73ea7679',
    'container.build_time' => 1606313643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGHxl3m');
