<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbyqqpi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbyqqpi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIbyqqpi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIbyqqpi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIbyqqpi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ibyqqpi',
    'container.build_id' => 'db95f137',
    'container.build_time' => 1605708634,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIbyqqpi');
