<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6H9kED\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6H9kED/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6H9kED.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6H9kED\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6H9kED\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6H9kED',
    'container.build_id' => '3646de47',
    'container.build_time' => 1606307095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6H9kED');
